image: cirrusci/flutter

variables:
before_script:
  - flutter channel stable
  - flutter upgrade

stages:
  - test
  - build

test:
  stage: test
  script:
    - cd ./example
    - flutter test

build:
  stage: build
  script:
    - cd ./example
    - flutter build apk --release
