name: spider_chart_color
description: Spider Chart is a simple spider/radar charting library for Flutter
version: 0.3.0
homepage: https://github.com/ahzam-shahnil/flutter-spider-chart.git

environment:
  sdk: ">=2.16.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
